# build succeds on pr
name: Build succeds on pr

on: # run on pull request on master branch
  pull_request:
    branches:
      -master
      # can add more branches
    

  jobs:
    build:
      name: build the project
      runs-on: ubuntu-latest # run github machine (azure since)
      steps:
        - uses: actions/checkout@v3 # clones the repo to github machine. this actions/checkout is already writen and audited by someone 
         # so we dont have to write long ass code 
        - name: Use Node.js # install node js on machine
          uses: actions/setup-node@v3  # this action already created by somone and we using that
          with: 
            node-version: '20'

        - name: Install Dependencies # runs npm install
          run: npm Install

        - name: Generate prisma client
          run: cd packages/db && npx prisma generate && cd ../..

        - name: Run build
          run: npm run build